-- Tone refresh: rename 'loving' → 'warm' and add three new values
-- (authoritative, inspirational, bold).
--
-- Drizzle's autogenerated diff for this change was a destructive
-- DROP TYPE / CREATE TYPE / cast-via-text round-trip. That fails in
-- prod because 13 existing creators rows still have tone = 'loving',
-- and the cast back to the new enum (which no longer contains 'loving')
-- raises `invalid input value for enum`. This hand-written migration
-- replaces that diff with in-place enum mutation:
--
--   1. RENAME VALUE 'loving' → 'warm'   (PG 10+; updates the label,
--      existing rows transparently reference the new label via internal
--      OID — no data UPDATE needed).
--   2. ADD VALUE for the three new tones, IF NOT EXISTS so re-running is
--      safe.
--
-- Note: ALTER TYPE ... ADD VALUE cannot run inside a transaction unless
-- the type was created in the same transaction. Each statement below is
-- separated by drizzle's statement-breakpoint marker so the migrator can
-- run them on their own connections without a wrapping BEGIN/COMMIT.
ALTER TYPE "public"."tone" RENAME VALUE 'loving' TO 'warm';--> statement-breakpoint
ALTER TYPE "public"."tone" ADD VALUE IF NOT EXISTS 'authoritative';--> statement-breakpoint
ALTER TYPE "public"."tone" ADD VALUE IF NOT EXISTS 'inspirational';--> statement-breakpoint
ALTER TYPE "public"."tone" ADD VALUE IF NOT EXISTS 'bold';
